import type { Patient, Vaccination, GrowthMeasurement, Appointment, MedicalRecord, Notification, User, DashboardStats, VaccinationSchedule } from './types';

export const currentUser: User = {
    id: '1',
    name: 'Dr. Kovács Anna',
    email: 'kovacs.anna@healthcare.hu',
    role: 'provider',
};

export const mockPatients: Patient[] = [
    {
        id: '1',
        firstName: 'Emma',
        lastName: 'Nagy',
        dateOfBirth: '2023-03-15',
        mothersMaidenName: 'Szabó',
        gender: 'female',
        nationalId: '123456789',
        birthWeight: 3200,
        birthLength: 49,
        birthHeadCircumference: 34,
        gestationalAge: 39,
    },
    {
        id: '2',
        firstName: 'Máté',
        middleName: 'István',
        lastName: 'Kiss',
        dateOfBirth: '2022-08-22',
        mothersMaidenName: 'Horváth',
        gender: 'male',
        nationalId: '987654321',
        birthWeight: 3450,
        birthLength: 51,
        birthHeadCircumference: 35,
        gestationalAge: 40,
    },
    {
        id: '3',
        firstName: 'Luca',
        lastName: 'Tóth',
        dateOfBirth: '2024-01-10',
        mothersMaidenName: 'Molnár',
        gender: 'female',
        nationalId: '456789123',
        birthWeight: 2980,
        birthLength: 48,
        birthHeadCircumference: 33,
        gestationalAge: 38,
    },
];

export const vaccinationSchedule: VaccinationSchedule[] = [
    { id: '1', vaccineName: 'BCG', ageInMonths: 0, isMandatory: true, description: 'Tuberculosis vaccine' },
    { id: '2', vaccineName: 'Hepatitis B', ageInMonths: 0, isMandatory: true, description: 'First dose at birth' },
    { id: '3', vaccineName: 'DTPa-IPV-Hib', ageInMonths: 2, isMandatory: true, description: 'Diphtheria, Tetanus, Pertussis, Polio, Haemophilus' },
    { id: '4', vaccineName: 'Pneumococcal', ageInMonths: 2, isMandatory: true, description: 'Pneumococcal conjugate vaccine' },
    { id: '5', vaccineName: 'Rotavirus', ageInMonths: 2, isMandatory: false, description: 'Rotavirus vaccine (recommended)' },
    { id: '6', vaccineName: 'DTPa-IPV-Hib', ageInMonths: 4, isMandatory: true, description: 'Second dose' },
    { id: '7', vaccineName: 'Pneumococcal', ageInMonths: 4, isMandatory: true, description: 'Second dose' },
    { id: '8', vaccineName: 'MMR', ageInMonths: 12, isMandatory: true, description: 'Measles, Mumps, Rubella' },
    { id: '9', vaccineName: 'Varicella', ageInMonths: 12, isMandatory: false, description: 'Chickenpox vaccine (recommended)' },
];

export const mockVaccinations: Vaccination[] = [
    {
        id: '1',
        patientId: '1',
        vaccineName: 'BCG',
        vaccineType: 'Tuberculosis',
        dateAdministered: '2023-03-16',
        batchNumber: 'BCG2023-001',
        provider: 'Dr. Kovács Anna',
        isMandatory: true,
        doseNumber: 1,
        totalDoses: 1,
    },
    {
        id: '2',
        patientId: '1',
        vaccineName: 'Hepatitis B',
        vaccineType: 'Hepatitis B',
        dateAdministered: '2023-03-16',
        batchNumber: 'HEPB2023-045',
        provider: 'Dr. Bodnár Erika',
        isMandatory: true,
        doseNumber: 1,
        totalDoses: 3,
        nextDueDate: '2023-05-15',
    },
    {
        id: '3',
        patientId: '1',
        vaccineName: 'DTPa-IPV-Hib',
        vaccineType: 'Combined',
        dateAdministered: '2023-05-15',
        batchNumber: 'DTP2023-112',
        provider: 'Dr. Kovács Anna',
        isMandatory: true,
        doseNumber: 1,
        totalDoses: 4,
        nextDueDate: '2023-07-15',
    },
    {
        id: '4',
        patientId: '2',
        vaccineName: 'MMR',
        vaccineType: 'Measles, Mumps, Rubella',
        dateAdministered: '2023-08-22',
        batchNumber: 'MMR2023-089',
        provider: 'Dr. Szabó Péter',
        isMandatory: true,
        doseNumber: 1,
        totalDoses: 2,
        nextDueDate: '2024-08-22',
    },
];

export const mockGrowthData: GrowthMeasurement[] = [
    {
        id: '1',
        patientId: '1',
        date: '2023-03-16',
        weight: 3.2,
        height: 49,
        headCircumference: 34,
        percentiles: { weight: 45, height: 50 },
    },
    {
        id: '2',
        patientId: '1',
        date: '2023-04-15',
        weight: 4.1,
        height: 52,
        headCircumference: 36,
        percentiles: { weight: 50, height: 52 },
    },
    {
        id: '3',
        patientId: '1',
        date: '2023-05-15',
        weight: 5.2,
        height: 55,
        headCircumference: 38,
        percentiles: { weight: 55, height: 55 },
    },
    {
        id: '4',
        patientId: '1',
        date: '2023-06-15',
        weight: 6.1,
        height: 58,
        headCircumference: 40,
        percentiles: { weight: 58, height: 57 },
    },
    {
        id: '5',
        patientId: '1',
        date: '2023-07-15',
        weight: 6.8,
        height: 61,
        headCircumference: 41,
        percentiles: { weight: 60, height: 60 },
    },
    {
        id: '6',
        patientId: '1',
        date: '2023-08-15',
        weight: 7.4,
        height: 63,
        headCircumference: 42,
        percentiles: { weight: 62, height: 62 },
    },
    {
        id: '7',
        patientId: '1',
        date: '2023-09-15',
        weight: 7.9,
        height: 65,
        headCircumference: 43,
        percentiles: { weight: 63, height: 63 },
    },
    {
        id: '8',
        patientId: '1',
        date: '2023-10-15',
        weight: 8.3,
        height: 67,
        headCircumference: 44,
        percentiles: { weight: 64, height: 64 },
    },
    {
        id: '9',
        patientId: '1',
        date: '2023-11-15',
        weight: 8.7,
        height: 69,
        headCircumference: 44.5,
        percentiles: { weight: 65, height: 65 },
    },
    {
        id: '10',
        patientId: '1',
        date: '2023-12-15',
        weight: 9.1,
        height: 71,
        headCircumference: 45,
        percentiles: { weight: 66, height: 66 },
    },
];

export const mockAppointments: Appointment[] = [
    {
        id: '1',
        patientId: '1',
        providerId: '1',
        providerName: 'Dr. Bodnár Erika',
        type: 'well-child',
        date: '2025-01-05',
        time: '10:00',
        status: 'scheduled',
        notes: '10-month checkup',
    },
    {
        id: '2',
        patientId: '2',
        providerId: '1',
        providerName: 'Dr. Kovács Anna',
        type: 'vaccination',
        date: '2025-01-08',
        time: '14:30',
        status: 'scheduled',
        notes: 'MMR second dose',
    },
    {
        id: '3',
        patientId: '3',
        providerId: '2',
        providerName: 'Dr. Szabó Péter',
        type: 'screening',
        date: '2025-01-10',
        time: '09:00',
        status: 'scheduled',
        notes: 'Newborn screening',
    },
    {
        id: '4',
        patientId: '1',
        providerId: '1',
        providerName: 'Dr. Kovács Anna',
        type: 'well-child',
        date: '2024-12-15',
        time: '11:00',
        status: 'completed',
        notes: '9-month checkup - all good',
    },
];

export const mockMedicalRecords: MedicalRecord[] = [
    {
        id: '1',
        patientId: '1',
        date: '2023-03-16',
        type: 'visit-note',
        title: 'Newborn Examination',
        provider: 'Dr. Bodnár Erika',
        diagnosis: 'Healthy newborn',
        treatment: 'No treatment needed',
    },
    {
        id: '2',
        patientId: '1',
        date: '2023-05-15',
        type: 'visit-note',
        title: '2-Month Checkup',
        provider: 'Dr. Kovács Anna',
        diagnosis: 'Normal development',
        treatment: 'Continue breastfeeding',
    },
    {
        id: '3',
        patientId: '1',
        date: '2023-08-15',
        type: 'document',
        title: 'Lab Results',
        description: 'Anemia screening',
        fileUrl: '#',
    },
];

export const mockNotifications: Notification[] = [
    {
        id: '1',
        type: 'appointment',
        title: 'Upcoming Appointment',
        message: 'Emma Nagy - 10-month checkup tomorrow at 10:00 AM',
        date: '2025-01-04',
        isRead: false,
        priority: 'high',
    },
    {
        id: '2',
        type: 'vaccination',
        title: 'Vaccination Due',
        message: 'Máté Kiss - MMR second dose within 3 days',
        date: '2025-01-05',
        isRead: false,
        priority: 'medium',
    },
    {
        id: '3',
        type: 'screening',
        title: 'Screening Appointment',
        message: 'Luca Tóth - Newborn screening on 2025-01-10',
        date: '2025-01-03',
        isRead: true,
        priority: 'low',
    },
];

export const dashboardStats: DashboardStats = {
    totalPatients: 3,
    upcomingAppointments: 3,
    pendingVaccinations: 5,
    recentCheckups: 1,
};
